### ISSUE TITLE
chakin: too many clients already

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/galaxy-tools#23]
Before I forget it: when launching many chakin load_fasta jobs in galaxy, I get this error in the logs, and the form dynamic option no longer work. Probably some sql config to do...
```
galaxy_1  | galaxy.tools.parameters.basic DEBUG 2018-08-08 15:46:05,089 [p:1106,w:1,m:0] [uWSGIWorker1Core0] Error determining dynamic options for parameter 'analysis_id' in tool 'toolshed.g2.bx.psu.edu/repos/gga/chado_feature_load_fasta/feature_load_fasta/2.1.5.0':
galaxy_1  | Traceback (most recent call last):
galaxy_1  |   File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
galaxy_1  |     return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
galaxy_1  |   File "<string>", line 1, in <module>
galaxy_1  |   File "../shed_tools/toolshed.g2.bx.psu.edu/repos/gga/chado_feature_load_fasta/48cad01fd762/chado_feature_load_fasta/chado.py", line 438, in list_analyses
galaxy_1  |     ci = _get_instance()
galaxy_1  |   File "../shed_tools/toolshed.g2.bx.psu.edu/repos/gga/chado_feature_load_fasta/48cad01fd762/chado_feature_load_fasta/chado.py", line 392, in _get_instance
galaxy_1  |     no_reflect=True
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/chado/__init__.py", line 49, in __init__
galaxy_1  |     self._test_db_access()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/chado/__init__.py", line 173, in _test_db_access
galaxy_1  |     tables = self._engine.table_names(schema=self.dbschema)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2136, in table_names
galaxy_1  |     with self._optional_conn_ctx_manager(connection) as conn:
galaxy_1  |   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
galaxy_1  |     return self.gen.next()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
galaxy_1  |     with self.contextual_connect() as conn:
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
galaxy_1  |     self._wrap_pool_connect(self.pool.connect, None),
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
galaxy_1  |     e, dialect, self)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
galaxy_1  |     exc_info
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
galaxy_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
galaxy_1  |     return fn()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 403, in connect
galaxy_1  |     return _ConnectionFairy._checkout(self)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
galaxy_1  |     fairy = _ConnectionRecord.checkout(pool)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 532, in checkout
galaxy_1  |     rec = pool._do_get()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
galaxy_1  |     self._dec_overflow()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
galaxy_1  |     compat.reraise(exc_type, exc_value, exc_tb)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
galaxy_1  |     return self._create_connection()
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
galaxy_1  |     return _ConnectionRecord(self)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 477, in __init__
galaxy_1  |     self.__connect(first_connect_check=True)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
galaxy_1  |     connection = pool._invoke_creator(self)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
galaxy_1  |     return dialect.connect(*cargs, **cparams)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 410, in connect
galaxy_1  |     return self.dbapi.connect(*cargs, **cparams)
galaxy_1  |   File "/galaxy_venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
galaxy_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
galaxy_1  | OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already

```

**Comment by erasche** [comment]
Fixed in #31
